require("ibl").setup({
    exclude = {
		filetypes = {
			"help",
			"terminal",
			"lazy",
			"lspinfo",
			"TelescopePrompt",
			"TelescopeResults",
			"mason",
			"nvdash",
			"nvcheatsheet",
			"NvimTree",
			"Trouble",
			"startify",
			"dashboard",
			"notify",
			"toggleterm",
			"alpha",
			"neo-tree",
			"",
		},
		buftypes = { "terminal", "nofile" },
	},
})