require 'plugins.tokyonight'
-- require 'plugins.oil'
require 'plugins.bufferline'
require 'plugins.mini'
-- require 'plugins.todo'
require 'plugins.floaterm'
require 'plugins.comment'
require 'plugins.conform'
require 'plugins.indent-blankline'
require 'plugins.gitsigns'
require 'plugins.fidget'
require 'plugins.neodev'
require 'plugins.treesitter'
require 'plugins.completion'
require 'plugins.lsp'
require 'plugins.telescope'
--require 'plugins.lualine'
require 'plugins.which-key'
